name: LucasEconomy
version: 1.0.0
main: LucasEconomy\Main
description: A new logic, easy Economy.
api: 5.0.0
author: Lucas
permissions:
  lucaseconomy.balance:
    description: "/balance."
    default: true
  lucaseconomy.pay:
    description: "/pay."
    default: true
  lucaseconomy.top:
    description: "/top."
    default: true
  lucaseconomy.seemoney:
    description: "/seemoney."
    default: true
  lucaseconomy.admin:
    description: "Admin commands."
    default: op